/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBacktestRouteImport } from './routes/_authenticated/backtest'
import { Route as ApiPublicMt5SignalsRouteImport } from './routes/api/public/mt5-signals'
import { Route as ApiPublicMt5FiboEaRouteImport } from './routes/api/public/mt5-fibo-ea'
import { Route as ApiPublicMt5ExportRouteImport } from './routes/api/public/mt5-export'
import { Route as ApiPublicEconCalendarRouteImport } from './routes/api/public/econ-calendar'
import { Route as ApiPublicHooksEvaluateSignalsRouteImport } from './routes/api/public/hooks/evaluate-signals'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBacktestRoute = AuthenticatedBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicMt5SignalsRoute = ApiPublicMt5SignalsRouteImport.update({
  id: '/api/public/mt5-signals',
  path: '/api/public/mt5-signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMt5FiboEaRoute = ApiPublicMt5FiboEaRouteImport.update({
  id: '/api/public/mt5-fibo-ea',
  path: '/api/public/mt5-fibo-ea',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMt5ExportRoute = ApiPublicMt5ExportRouteImport.update({
  id: '/api/public/mt5-export',
  path: '/api/public/mt5-export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEconCalendarRoute = ApiPublicEconCalendarRouteImport.update({
  id: '/api/public/econ-calendar',
  path: '/api/public/econ-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEvaluateSignalsRoute =
  ApiPublicHooksEvaluateSignalsRouteImport.update({
    id: '/api/public/hooks/evaluate-signals',
    path: '/api/public/hooks/evaluate-signals',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof AuthenticatedBacktestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/econ-calendar': typeof ApiPublicEconCalendarRoute
  '/api/public/mt5-export': typeof ApiPublicMt5ExportRoute
  '/api/public/mt5-fibo-ea': typeof ApiPublicMt5FiboEaRoute
  '/api/public/mt5-signals': typeof ApiPublicMt5SignalsRoute
  '/api/public/hooks/evaluate-signals': typeof ApiPublicHooksEvaluateSignalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof AuthenticatedBacktestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/econ-calendar': typeof ApiPublicEconCalendarRoute
  '/api/public/mt5-export': typeof ApiPublicMt5ExportRoute
  '/api/public/mt5-fibo-ea': typeof ApiPublicMt5FiboEaRoute
  '/api/public/mt5-signals': typeof ApiPublicMt5SignalsRoute
  '/api/public/hooks/evaluate-signals': typeof ApiPublicHooksEvaluateSignalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/backtest': typeof AuthenticatedBacktestRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/public/econ-calendar': typeof ApiPublicEconCalendarRoute
  '/api/public/mt5-export': typeof ApiPublicMt5ExportRoute
  '/api/public/mt5-fibo-ea': typeof ApiPublicMt5FiboEaRoute
  '/api/public/mt5-signals': typeof ApiPublicMt5SignalsRoute
  '/api/public/hooks/evaluate-signals': typeof ApiPublicHooksEvaluateSignalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/backtest'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/api/public/econ-calendar'
    | '/api/public/mt5-export'
    | '/api/public/mt5-fibo-ea'
    | '/api/public/mt5-signals'
    | '/api/public/hooks/evaluate-signals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/backtest'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/api/public/econ-calendar'
    | '/api/public/mt5-export'
    | '/api/public/mt5-fibo-ea'
    | '/api/public/mt5-signals'
    | '/api/public/hooks/evaluate-signals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/backtest'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/settings'
    | '/api/public/econ-calendar'
    | '/api/public/mt5-export'
    | '/api/public/mt5-fibo-ea'
    | '/api/public/mt5-signals'
    | '/api/public/hooks/evaluate-signals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicEconCalendarRoute: typeof ApiPublicEconCalendarRoute
  ApiPublicMt5ExportRoute: typeof ApiPublicMt5ExportRoute
  ApiPublicMt5FiboEaRoute: typeof ApiPublicMt5FiboEaRoute
  ApiPublicMt5SignalsRoute: typeof ApiPublicMt5SignalsRoute
  ApiPublicHooksEvaluateSignalsRoute: typeof ApiPublicHooksEvaluateSignalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backtest': {
      id: '/_authenticated/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof AuthenticatedBacktestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/mt5-signals': {
      id: '/api/public/mt5-signals'
      path: '/api/public/mt5-signals'
      fullPath: '/api/public/mt5-signals'
      preLoaderRoute: typeof ApiPublicMt5SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mt5-fibo-ea': {
      id: '/api/public/mt5-fibo-ea'
      path: '/api/public/mt5-fibo-ea'
      fullPath: '/api/public/mt5-fibo-ea'
      preLoaderRoute: typeof ApiPublicMt5FiboEaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mt5-export': {
      id: '/api/public/mt5-export'
      path: '/api/public/mt5-export'
      fullPath: '/api/public/mt5-export'
      preLoaderRoute: typeof ApiPublicMt5ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/econ-calendar': {
      id: '/api/public/econ-calendar'
      path: '/api/public/econ-calendar'
      fullPath: '/api/public/econ-calendar'
      preLoaderRoute: typeof ApiPublicEconCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/evaluate-signals': {
      id: '/api/public/hooks/evaluate-signals'
      path: '/api/public/hooks/evaluate-signals'
      fullPath: '/api/public/hooks/evaluate-signals'
      preLoaderRoute: typeof ApiPublicHooksEvaluateSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBacktestRoute: typeof AuthenticatedBacktestRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBacktestRoute: AuthenticatedBacktestRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicEconCalendarRoute: ApiPublicEconCalendarRoute,
  ApiPublicMt5ExportRoute: ApiPublicMt5ExportRoute,
  ApiPublicMt5FiboEaRoute: ApiPublicMt5FiboEaRoute,
  ApiPublicMt5SignalsRoute: ApiPublicMt5SignalsRoute,
  ApiPublicHooksEvaluateSignalsRoute: ApiPublicHooksEvaluateSignalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
